version: "3"
services:
  subject_db:
    build:
      context: .
      dockerfile: "dockerfiles/db/Dockerfile"
    environment:
      - MYSQL_TCP_PORT=3307
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/disk/db/var/lib/mysql:/var/lib/mysql
  subject_web:
    build:
      context: .
      dockerfile: "dockerfiles/web/Dockerfile"
    environment:
      RAILS_ENV: development
      NODE_ENV: development
    ports:
      - "3000:3000"
    command: "bash"
    tty: true
    stdin_open: true
    privileged: false
    volumes:
      - ./rails-app:/rails-app
    links:
      - subject_db
    depends_on:
      - subject_db